import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ProviderElement from "@/lib/provider";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import AppBreadcrumb from "@/components/app-breadcrumb";
import ThemeChanger from "@/components/theme-changer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProviderElement>
      <html lang="en">
        <head>
          <title>V-UI</title>
          <link rel="icon" href="/favicon.ico" type="image/x-icon" />
          <meta name="description" content="Description of your product" />
          <meta
            name="keywords"
            content="vui, UI, UI Library, framer-motion, motion, animated, components, tailwind, aceternity"
          />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="flex h-16 shrink-0 items-center gap-2 border-b">
                <div className="flex items-center gap-2 px-3 w-full">
                  <SidebarTrigger />
                  <Separator orientation="vertical" className="mr-2 h-4" />
                  <AppBreadcrumb />
                  <ThemeChanger />
                </div>
              </header>
              {children}
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </ProviderElement>
  );
}
